//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalariaEntities2 : DbContext
    {
        public MalariaEntities2()
            : base("name=MalariaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogIn> LogIns { get; set; }
        public virtual DbSet<Malaria_Areas> Malaria_Areas { get; set; }
        public virtual DbSet<Malaria_Controls> Malaria_Controls { get; set; }
        public virtual DbSet<Malaria_Facts> Malaria_Facts { get; set; }
        public virtual DbSet<Malaria_Log> Malaria_Log { get; set; }
        public virtual DbSet<Malaria_Prevention> Malaria_Prevention { get; set; }
        public virtual DbSet<Malaria_Treatments> Malaria_Treatments { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserLevel> UserLevels { get; set; }
        public virtual DbSet<UserName> UserNames { get; set; }
    }
}
