//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malaria_Log
    {
        public int Log_ID { get; set; }
        public Nullable<int> fk_MT_ID { get; set; }
        public Nullable<int> fk_MC_ID { get; set; }
        public Nullable<int> fk_MF_ID { get; set; }
        public Nullable<int> fk_MA_ID { get; set; }
        public Nullable<int> fk_MP_ID { get; set; }
        public Nullable<int> User_Name_ID { get; set; }
    
        public virtual Malaria_Areas Malaria_Areas { get; set; }
        public virtual Malaria_Controls Malaria_Controls { get; set; }
        public virtual Malaria_Facts Malaria_Facts { get; set; }
        public virtual Malaria_Prevention Malaria_Prevention { get; set; }
        public virtual Malaria_Treatments Malaria_Treatments { get; set; }
        public virtual UserName UserName { get; set; }
    }
}
