//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malariav2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malaria_Facts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malaria_Facts()
        {
            this.Malaria_Log = new HashSet<Malaria_Log>();
        }
    
        public int ID { get; set; }
        public string Facts_Details { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malaria_Log> Malaria_Log { get; set; }
        public ICollection<Malaria_Areas> Malaria_Areas { get; set; }
    }
}
